name: CI
on:
  pull_request:
  push:
    branches: main
defaults:
  run:
    shell: bash
concurrency:
  group: CI-${{ github.ref }}
  # Queue on all branches and tags, but only cancel overlapping PR burns.
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' || !startsWith(github.ref, 'refs/tags/') }}
jobs:
  org-check:
    name: Check GitHub Organization
    if: github.repository_owner == 'pex-tool'
    runs-on: ubuntu-24.04
    steps:
      - name: Noop
        run: "true"
  tests-36-38:
    name: (${{ matrix.os }}) Python ${{ matrix.python-version[0] }}.${{ matrix.python-version[1] }} Tests
    needs: org-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15]
        python-version: [[3, 6, 15], [3, 7, 17], [3, 8, 18]]
    steps:
      - name: Checkout p537
        uses: actions/checkout@v5
      - name: "Setup Python ${{ join(matrix.python-version, '.') }}"
        # Upgrade node16 -> node20: Out for review here:
        #   https://github.com/gabrielfalcao/pyenv-action/pull/444
        uses: pex-tool/pyenv-action@baec18679698d2f80064cc04eb9ad0c8dc5ca8f8
        env:
          ENSUREPIP: no
        with:
          default: "${{ join(matrix.python-version, '.') }}"
          command: pip install -U tox
      - name: Run Unit Tests
        run: tox -e py${{ matrix.python-version[0] }}${{ matrix.python-version[1] }}
  tests-39-315:
    name: (${{ matrix.os }}) Python 3.9 - 3.15 Tests
    needs: org-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15, macos-15-arm, windows-2025]
    steps:
      - name: Checkout p537
        uses: actions/checkout@v5
      - name: Setup Python 3.9
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"
      - name: Setup Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Setup Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Setup Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Setup Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Setup Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Setup Python 3.15
        uses: actions/setup-python@v6
        with:
          python-version: "3.15.0-alpha.1"
      - name: Run Unit Tests
        uses: pex-tool/actions/run-tox@7d8530c74d2e3ca4640d1ed9192b6e2b8c4f5f7b
        with:
          tox-env: py39,py310,py311,py312,py313,py314,py315
  final-status:
    name: Gather Final Status
    needs:
      - tests-36-38
      - tests-39-315
    runs-on: ubuntu-24.04
    steps:
      - name: Check Non-Success
        if: |
          contains(needs.*.result, 'cancelled') ||
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'skipped')
        run: "false"
      - name: Success
        run: "true"
