name: CI
on:
  pull_request:
  push:
    branches: master
defaults:
  run:
    shell: bash
concurrency:
  group: CI-${{ github.ref }}
  # Queue on all branches and tags, but only cancel overlapping PR burns.
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' || !startsWith(github.ref, 'refs/tags/') }}
jobs:
  org-check:
    name: Check GitHub Organization
    if: github.repository_owner == 'jsirois'
    runs-on: ubuntu-20.04
    steps:
      - name: Noop
        run: "true"
  tests:
    name: (${{ matrix.os }}) Tests
    needs: org-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2022]
    steps:
      - name: Checkout p537
        uses: actions/checkout@v3
      - name: Setup Python 3.6
        uses: actions/setup-python@v4
        with:
          python-version: "3.6"
      - name: Setup Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0-rc.2"
      - name: Run Unit Tests
        uses: pantsbuild/actions/run-tox@95209b287c817c78a765962d40ac6cea790fc511
        with:
          tox-env: py36,py37,py38,py39,py310,py311
  final-status:
    name: Gather Final Status
    needs:
      - tests
    runs-on: ubuntu-20.04
    steps:
      - name: Check Non-Success
        if: |
          contains(needs.*.result, 'cancelled') ||
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'skipped')
        run: "false"
      - name: Success
        run: "true"
